#!/bin/bash
# chkconfig: 345 20 80
# description: File Export Service start/shutdown script
# processname: fes
# config: /etc/avail/fes/fes.cfg
#

# source function library
. /etc/rc.d/init.d/functions

# Path to fes install folder
FES=/opt/fes/fes.py
FES_OPTS="--debug --daemon"
LOCKFILE=/var/lock/subsys/fes

RETVAL=0

d_start() {
    echo -n $"Starting FES service: "
    daemon $FES $FES_OPTS && success || failure
    RETVAL=$?
    echo
    return $RETVAL
}

d_stop() {
    echo -n $"Stopping FES service: "

    if [ -f $LOCKFILE ]; then
        killproc -p $LOCKFILE $FES
    else
        failure $"Stopping FES service"
    fi
    RETVAL=$?

    [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
    echo
}

d_restart() {
    d_stop
    sleep 1
    d_start
}

d_status() {
    status -p $LOCKFILE $FES
}

d_status_q() {
    d_status >/dev/null 2>&1
}

case "$1" in
    start)
        d_status_q && exit 0
        if [ $? -ne 0 -a -f $LOCKFILE ]; then
            echo 'Removing lock file from dead pid.'
            rm -f $LOCKFILE
        fi
        d_start
        ;;
    stop)
        if ! d_status_q; then
            rm -rf $LOCKFILE
            exit 0
        fi
        d_stop
        ;;
    restart)
        d_restart
        ;;
    status)
        d_status
        RETVAL=$?
        if [ $RETVAL -eq 3 -a -f $LOCKFILE ]; then
            RETVAL=2
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        RETVAL=2
        ;;
esac
exit $RETVAL
